<!--Do NOT change this file manually, it is being generated by svgicons script.-->

<template>
    <component v-bind:is="component"/>
</template>

<script lang="ts">
    import Vue from 'vue';
    import {_startcase} from "@/config/util";
    import ArrowDown from '@/assets/svg/ico-arrow-down.svg';
    import ArrowLeft from '@/assets/svg/ico-arrow-left.svg';
    import ArrowRight from '@/assets/svg/ico-arrow-right.svg';
    import ArrowUp from '@/assets/svg/ico-arrow-up.svg';
    import Close from '@/assets/svg/ico-close.svg';
    import Happy from '@/assets/svg/ico-happy.svg';
    import QuoteLeft from '@/assets/svg/ico-quote-left.svg';
    import QuoteRight from '@/assets/svg/ico-quote-right.svg';

    export default Vue.extend({
        props: {
            iconName: {
                type: String,
                required: true
            }
        },
        components: {
            ArrowDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            Close,
            Happy,
            QuoteLeft,
            QuoteRight,

        },
        computed: {
            component() {
                return _startcase(this.iconName.replace('ico-', '')).replace(' ', '');
            }
        }
    });
</script>
